site_name: 'Epirus Blockchain Explorer'
site_description: 'Documentation portal for the Epirus Blockchain Explorer'
site_author: 'Web3 Labs'
site_url: 'https://www.web3labs.com'

# Repository
repo_name: 'blk-io/epirus.github.io'
repo_url: 'https://github.com/blk-io/epirus.github.io'

# Copyright
copyright: 'Copyright &copy; 2017-2019 Web3 Labs Ltd'

nav:
- 'index.md'
- 'getting_started.md'
- 'features.md'
- 'metadata.md'
- 'tagging.md'
- 'rest.md'
- 'faqs.md'

# Configuration
theme:
  name: 'material'
  custom_dir: 'theme'
  language: 'en'
  logo: 'img/web3labs_logo.png'
  favicon: 'img/favicon.ico'

# Customization
extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/blk-io'
    - type: 'twitter'
      link: 'https://twitter.com/web3labs'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/web3labs'

extra_css:
  - 'stylesheets/extra.css'

# Google Analytics
google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.details
  - toc:
      permalink: true
      toc_depth: 3

